### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by DipDipPotatoChips** [cv-rits/MonoScene#1]
(monoscene) ruidong@ubuntu-X299-UD4-Pro:~/workplace/MonoScene$ python monoscene/scripts/train_monoscene.py     dataset=kitti     enable_log=true     kitti_root=$KITTI_ROOT     kitti_preprocess_root=$KITTI_PREPROCESS    kitti_logdir=$KITTI_LOG     n_gpus=2 batch_size=2
^[[Dexp_kitti_1_FrusSize_8_nRelations4_WD0.0001_lr0.0001_CEssc_geoScalLoss_semScalLoss_fpLoss_CERel_3DCRP_Proj_2_4_8
n_relations (32, 32, 4)
Traceback (most recent call last):
  File "monoscene/scripts/train_monoscene.py", line 118, in main
    class_weights=class_weights,
  File "/home/ruidong/workplace/MonoScene/monoscene/models/monoscene.py", line 80, in __init__
    context_prior=context_prior,
  File "/home/ruidong/workplace/MonoScene/monoscene/models/unet3d_kitti.py", line 62, in __init__
    self.feature * 4, self.feature * 4, size_l3, bn_momentum=bn_momentum
  File "/home/ruidong/workplace/MonoScene/monoscene/models/CRP3D.py", line 15, in __init__
    self.flatten_size = size[0] * size[1] * size[2]
TypeError: 'int' object is not subscriptable

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by DipDipPotatoChips** [comment]
I use to GPUs，maybe should I change anything in the codes?

**Comment by anhquancao** [comment]
Hello @DipDipPotatoChips

Thank you for pointing out the error!
The command you use to train on 2 GPUs is correct. 

I fixed the error and pushed it. Could you pull the new commit and rerun 
```
pip install -e ./
```

**Comment by DipDipPotatoChips** [comment]
> Hello @DipDipPotatoChips
> 
> Thank you for pointing out the error! The command you use to train on 2 GPUs is correct.
> 
> I fixed the error and pushed it. Could you pull the new commit and rerun
> 
> ```
> pip install -e ./
> ```
(monoscene) ruidong@ubuntu-X299-UD4-Pro:~/workplace/MonoScene$ python monoscene/scripts/train_monoscene.py     dataset=kitti     enable_log=true     kitti_root=$KITTI_ROOT     kitti_preprocess_root=$KITTI_PREPROCESS    kitti_logdir=$KITTI_LOG     n_gpus=2 batch_size=2
exp_kitti_1_FrusSize_8_nRelations4_WD0.0001_lr0.0001_CEssc_geoScalLoss_semScalLoss_fpLoss_CERel_3DCRP_Proj_2_4_8
n_relations 4
Using cache found in /home/ruidong/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/tf_efficientnet_b7_ns-1dbc32de.pth" to /home/ruidong/.cache/torch/hub/checkpoints/tf_efficientnet_b7_ns-1dbc32de.pth
Traceback (most recent call last):
  File "monoscene/scripts/train_monoscene.py", line 118, in main
    class_weights=class_weights,
  File "/home/ruidong/workplace/MonoScene/monoscene/models/monoscene.py", line 82, in __init__
    self.net_rgb = UNet2D.build(out_feature=feature, use_decoder=True)
  File "/home/ruidong/workplace/MonoScene/monoscene/models/unet2d.py", line 181, in build
    "rwightman/gen-efficientnet-pytorch", basemodel_name, pretrained=True
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/site-packages/torch/hub.py", line 364, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/site-packages/torch/hub.py", line 393, in _load_local
    model = entry(*args, **kwargs)
  File "/home/ruidong/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/gen_efficientnet.py", line 1247, in tf_efficientnet_b7_ns
    'tf_efficientnet_b7_ns', channel_multiplier=2.0, depth_multiplier=3.1, pretrained=pretrained, **kwargs)
  File "/home/ruidong/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/gen_efficientnet.py", line 544, in _gen_efficientnet
    model = _create_model(model_kwargs, variant, pretrained)
  File "/home/ruidong/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/gen_efficientnet.py", line 290, in _create_model
    load_pretrained(model, model_urls[variant])
  File "/home/ruidong/.cache/torch/hub/rwightman_gen-efficientnet-pytorch_master/geffnet/helpers.py", line 39, in load_pretrained
    state_dict = load_state_dict_from_url(url, progress=False, map_location='cpu')
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/site-packages/torch/hub.py", line 553, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/site-packages/torch/hub.py", line 419, in download_url_to_file
    u = urlopen(req)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/urllib/request.py", line 1353, in do_open
    r = h.getresponse()
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Loading base model ()...

First it print another similar bug.I use a vpn and it failed with above message.

**Comment by anhquancao** [comment]
Hello @DipDipPotatoChips 

It seems that you cannot download the pre-trained efficient net checkpoint at
https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/tf_efficientnet_b7_ns-1dbc32de.pth
I guess your VPN blocks the connection from outside.

I propose you download the checkpoint manually and move it to 
```
/home/ruidong/.cache/torch/hub/checkpoints/tf_efficientnet_b7_ns-1dbc32de.pth
```

**Comment by DipDipPotatoChips** [comment]
> Hello @DipDipPotatoChips
> 
> It seems that you cannot download the pre-trained EfficientNet checkpoint at https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/tf_efficientnet_b7_ns-1dbc32de.pth I guess your VPN blocks the connection from outside.
> 
> I propose you download the checkpoint manually and move it to
> 
> ```
> /home/ruidong/.cache/torch/hub/checkpoints/tf_efficientnet_b7_ns-1dbc32de.pth
> ```

I git pull and retry,when I trdied to train it printed:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruidong/workplace/MonoScene/dataset/semantic_kitti/dataset/sequences/00/calib.txt'

![image](https://user-images.githubusercontent.com/48906782/146628600-29acfda0-8cb9-4c22-aec4-16a788ba29e1.png)

I have downloaded this two and tried them both  separately and followed the readme.md  to use:
`python monoscene/data/semantic_kitti/preprocess.py kitti_root=$KITTI_ROOT kitti_preprocess_root=$KITTI_PREPROCESS`

It still reported the error

**Comment by DipDipPotatoChips** [comment]
> > Hello @DipDipPotatoChips
> > It seems that you cannot download the pre-trained EfficientNet checkpoint at https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/tf_efficientnet_b7_ns-1dbc32de.pth I guess your VPN blocks the connection from outside.
> > I propose you download the checkpoint manually and move it to
> > ```
> > /home/ruidong/.cache/torch/hub/checkpoints/tf_efficientnet_b7_ns-1dbc32de.pth
> > ```
> 
> I git pull and retry,when I trdied to train it printed: FileNotFoundError: [Errno 2] No such file or directory: '/home/ruidong/workplace/MonoScene/dataset/semantic_kitti/dataset/sequences/00/calib.txt'
> 
> ![image](https://user-images.githubusercontent.com/48906782/146628600-29acfda0-8cb9-4c22-aec4-16a788ba29e1.png)
> 
> I have downloaded this two and tried them both separately and followed the readme.md to use: `python monoscene/data/semantic_kitti/preprocess.py kitti_root=$KITTI_ROOT kitti_preprocess_root=$KITTI_PREPROCESS`
> 
> It still reported the error

Need I download the above three links?

**Comment by anhquancao** [comment]
Yes, you need to download the KITTI Odometry Benchmark calibration data.

**Comment by DipDipPotatoChips** [comment]
> nload the KITTI Odometry Benchmark

I don't need to download the 80gb data KITTI Odometry Benchmark Velodyne point clouds,right?

**Comment by anhquancao** [comment]
Yes, you don't need the Velodyne point clouds

**Comment by DipDipPotatoChips** [comment]
> Yes, you don't need the Velodyne point clouds

I have downloaded all the zip file except the point clouds and used the data processing command but it still said could't find the png file:

FileNotFoundError: [Errno 2] No such file or directory: '/home/ruidong/workplace/MonoScene/dataset/semantic_kitti/dataset/sequences/08/image_2/000648.png'

So how can I get the png file?

**Comment by anhquancao** [comment]
Hello @DipDipPotatoChips,

Thank you for your patience! I will update the instruction on downloading the dataset.
You can get the RGB images from here
http://www.cvlibs.net/datasets/kitti/eval_odometry.php
![Screenshot from 2021-12-18 14-28-31](https://user-images.githubusercontent.com/9668858/146642746-aafbec0a-6f59-4070-bd45-8c3a5d43e3d9.png)

**Comment by DipDipPotatoChips** [comment]
> Hello @DipDipPotatoChips,
> 
> Thank you for your patience! I will update the instruction on downloading the dataset. You can get the RGB images from here http://www.cvlibs.net/datasets/kitti/eval_odometry.php ![Screenshot from 2021-12-18 14-28-31](https://user-images.githubusercontent.com/9668858/146642746-aafbec0a-6f59-4070-bd45-8c3a5d43e3d9.png)

thanks for replying patiently,a 65gb file from outside the site is a big question for me.I will reply as soon as there is any progress。π_π

**Comment by DipDipPotatoChips** [comment]
> > Hello @DipDipPotatoChips,
> > Thank you for your patience! I will update the instruction on downloading the dataset. You can get the RGB images from here http://www.cvlibs.net/datasets/kitti/eval_odometry.php ![Screenshot from 2021-12-18 14-28-31](https://user-images.githubusercontent.com/9668858/146642746-aafbec0a-6f59-4070-bd45-8c3a5d43e3d9.png)
> 
> thanks for replying patiently,a 65gb file from outside the site is a big question for me.I will reply as soon as there is any progress。π_π

![image](https://user-images.githubusercontent.com/48906782/146672530-8e56b3e6-6991-40eb-9155-975c6d4b695e.png)

I have gotten those data,I want to confirm which ones I should use.

**Comment by DipDipPotatoChips** [comment]
> > > Hello @DipDipPotatoChips,
> > > Thank you for your patience! I will update the instruction on downloading the dataset. You can get the RGB images from here http://www.cvlibs.net/datasets/kitti/eval_odometry.php ![Screenshot from 2021-12-18 14-28-31](https://user-images.githubusercontent.com/9668858/146642746-aafbec0a-6f59-4070-bd45-8c3a5d43e3d9.png)
> > 
> > 
> > thanks for replying patiently,a 65gb file from outside the site is a big question for me.I will reply as soon as there is any progress。π_π
> 
> ![image](https://user-images.githubusercontent.com/48906782/146672530-8e56b3e6-6991-40eb-9155-975c6d4b695e.png)
> 
> I have gotten those data,I want to confirm which ones I should use.

could you please tell me what's the difference between data_odometry_voxels.zip and data_odometry_voxels_all.zip?

**Comment by anhquancao** [comment]
You only need the data_odometry_voxels.zip, 
The data_odometry_voxels_all.zip contains all the frames e.g. 1, 2, 3, 4, 5 ...
The data_odometry_voxels.zip is a subset of data_odometry_voxels_all.zip that contains the frames with an interval of 5 e.g. 0, 5, 10, ...

**Comment by DipDipPotatoChips** [comment]
> You only need the data_odometry_voxels.zip, The data_odometry_voxels_all.zip contains all the frames e.g. 1, 2, 3, 4, 5 ... The data_odometry_voxels.zip is a subset of data_odometry_voxels_all.zip that contains the frames with an interval of 5 e.g. 0, 5, 10, ...

I've solved the data set problem，but when I tried to train,It still said:
File "/home/ruidong/workplace/MonoScene/monoscene/scripts/train_monoscene.py", line 169, in main
    trainer.fit(model, data_module)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 522, in fit
    self._run(model)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 830, in _run
    self._call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1125, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/home/ruidong/anaconda3/envs/monoscene/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py", line 440, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/ruidong/workplace/MonoScene/monoscene/data/semantic_kitti/kitti_dm.py", line 34, in setup
    color_jitter=(0.4, 0.4, 0.4),
  File "/home/ruidong/workplace/MonoScene/monoscene/data/semantic_kitti/kitti_dataset.py", line 54, in __init__
    os.path.join(self.root, "dataset", "sequences", sequence, "calib.txt")
  File "/home/ruidong/workplace/MonoScene/monoscene/data/semantic_kitti/kitti_dataset.py", line 199, in read_calib
    calib_out["Tr"][:3, :4] = calib_all["Tr"].reshape(3, 4)
KeyError: 'Tr'
I think the problem is still about the dataset?

**Comment by anhquancao** [comment]
I found the problem, you need to download the calibration from this website
http://www.cvlibs.net/datasets/kitti/eval_odometry.php
Download odometry data set (calibration files, 1 MB)
I am not sure why it's different from the one on the semantic KITTI website.

**Comment by DipDipPotatoChips** [comment]
> I found the problem, you need to download the calibration from this website http://www.cvlibs.net/datasets/kitti/eval_odometry.php Download odometry data set (calibration files, 1 MB) I am not sure why it's different from the one on the semantic KITTI website.

I downloaded that file and it works,but now it seems that the gpu is out of memory,I used:
`python monoscene/scripts/train_monoscene.py     dataset=kitti     enable_log=true     kitti_root=$KITTI_ROOT     kitti_preprocess_root=$KITTI_PREPROCESS    kitti_logdir=$KITTI_LOG     n_gpus=2 batch_size=2`

RuntimeError: CUDA out of memory. Tried to allocate 6.75 GiB (GPU 1; 23.70 GiB total capacity; 14.05 GiB already allocated; 1.61 GiB free; 20.35 GiB reserved in total by PyTorch)

But I use two 3090 with 24GB memory.

**Comment by anhquancao** [comment]
1 item needs a Tesla V100 32g to train.
You can try to reduce the feature size here e.g. to 32
https://github.com/cv-rits/MonoScene/blob/master/monoscene/scripts/train_monoscene.py#L54

**Comment by DipDipPotatoChips** [comment]
> 1 item needs a Tesla V100 32g to train. You can try to reduce the feature size here e.g. to 32 https://github.com/cv-rits/MonoScene/blob/master/monoscene/scripts/train_monoscene.py#L54
> 
> Or deactivate the 3DCRP here by setting context_prior to false https://github.com/cv-rits/MonoScene/blob/master/monoscene/config/monoscene.yaml#L26

I changed the feature size to 32 and it‘s training successfully.Thanks for your patience!
At last I want to asking a little bit more about how do these two approaches and especially the second approach affect the outcome?

**Comment by anhquancao** [comment]
Awesome! I am pleased to hear that.
Concerning the feature size, I am not sure but I don't think it will decrease much the performance.
About without the 3D CRP, you can check table 3 in our paper.
https://arxiv.org/pdf/2112.00726.pdf

Regarding the batch size of 2, it affects the batch norm and the number of steps per epoch. I never tried this setting so I am not sure what will be the outcome.
