### ISSUE TITLE
about calib.txt file

### ISSUE THREAD

**Issue by DipDipPotatoChips** [cv-rits/MonoScene#10]
I looked through a lot of blogs and found very little description of these parameters. The code in pykitti also does not specify what the data is. I only know that this is related to the camera intrinsics.Could you please give me a general explanation of these parameters？

**Comment by anhquancao** [comment]
Hi @DipDipPotatoChips,
I also cannot find the official description of these parameters but by checking other works, I believe that each row of the calib file contains the flatten 4x4 transformation matrix where:
- Tr: is the camera transformation that converts lidar points from the Lidar cooridnate to camera coordinate
- P0, P1, P2, P3: the camera intrinsics of cam0, ..., cam3 that are used to project the lidar points in camera coordinate to pixel locations.
You can find the setup of cam0,...,cam3 in the figure in the following link
http://www.cvlibs.net/datasets/kitti/setup.php

**Comment by DipDipPotatoChips** [comment]
> Hi @DipDipPotatoChips, I also cannot find the official description of these parameters but by checking other works, I believe that each row of the calib file contains the flatten 4x4 transformation matrix where:
> 
> * Tr: is the camera transformation that converts lidar points from the Lidar cooridnate to camera coordinate
> * P0, P1, P2, P3: the camera intrinsics of cam0, ..., cam3 that are used to project the lidar points in camera coordinate to pixel locations.
>   You can find the setup of cam0,...,cam3 in the figure in the following link
>   http://www.cvlibs.net/datasets/kitti/setup.php

Thanks,combined with the links, I have read the code and basically understood these processes
