### ISSUE TITLE
Add the semantic category of blind path during training

### ISSUE THREAD

**Issue by SZUshenyan** [cv-rits/MonoScene#103]
Hello, I want to add the semantic category of blind path during training. May I ask if I can only collect image data and voxel the image data into the format of semantic kitti dataset?

**Comment by anhquancao** [comment]
Hi, sorry I don't understand what do you mean. What is blind path? How can you voxel the image data?

**Comment by SZUshenyan** [comment]
> Hi, sorry I don't understand what do you mean. What is blind path? How can you voxel the image data?

1.Blind path is tactile pavement, it is also blind road for visually impaired individuals.
2.For the left and right views with blind road information collected by ZED camera, I only annotated blind road data, then converted binocular image data into point cloud data, and finally converted point cloud data into voxel data.

**Comment by anhquancao** [comment]
Yes, you can add it as a semantic class, I don't see any issue.
