### ISSUE TITLE
How did you get the occupancy labels of the NYUv2 dataset?

### ISSUE THREAD

**Issue by zicha4555** [cv-rits/MonoScene#104]
Thanks for your great job! 
Since I noticed that the download url in the page contains "monoscene", I want to know how do you get the occupancy labels of the NYUv2 dataset? I have not found it in official web page and paper of NYUv2 dataset, even though it is mentioned in the paper of MonoScene that "_NYUv2 [58] has 1449 Kinect captured indoor scenes, encoded as 240x144x240 voxel grids labeled with 13 classes_". If you generated the occupancy labels, could you please provide more details about the way you did it?

**Comment by anhquancao** [comment]
Hi @zicha4555, please take a look at [this issue](https://github.com/astra-vision/MonoScene/issues/40).

**Comment by zicha4555** [comment]
> Hi @zicha4555, please take a look at [this issue](https://github.com/astra-vision/MonoScene/issues/40).

Thank you for replying! After researching, I learned that this SSC annotations of NYU was produced by SSCNet, through voxelizing the 3D models of NYU scenes, which was made by another work titled as "Support surfaces prediction for indoor scene understanding."

**Comment by anhquancao** [comment]
You are right!
