### ISSUE TITLE
Question Regarding Model Evaluation Metrics

### ISSUE THREAD

**Issue by 5orryMaker** [cv-rits/MonoScene#105]
I have a question regarding the evaluation metrics of the model. When using the official pre-trained model for evaluation, the results are as follows:
Precision=52.1908, Recall=55.5026, IoU=36.7950
class IoU: ['empty', 'car', 'bicycle', 'motorcycle', 'truck', 'other-vehicle', 'person', 'bicyclist', 'motorcyclist', 'road', 'parking', 'sidewalk', 'other-ground', 'building', 'fence', 'vegetation', 'trunk', 'terrain', 'pole', 'traffic-sign'],
92.1436,  23.2907,  0.2791,  0.5933,  9.2888,  2.6358,  1.9983,  1.0710,  0.0000,  55.8938,  14.7529,  26.5019,  1.6310,  13.5479,  6.6017,  17.9811,  2.4370,  29.8437,  3.9073,  2.4322,
mIoU=11.2993
My question is about the IoU value listed after Precision and Recall: which category does this IoU correspond to? It is not clearly indicated, and based on the calculation, it doesn't seem to be a misreported F1 score either.

Could you please clarify which category or metric this IoU corresponds to?

Thank you for your assistance!

**Comment by anhquancao** [comment]
Hi, it is the Geometry IoU which considers all semantic voxels as single class (occupied voxel).

**Comment by 5orryMaker** [comment]
get it. thank you very much!!
