### ISSUE TITLE
cannot find calib

### ISSUE THREAD

**Issue by cyaccpect** [cv-rits/MonoScene#14]
PS F:\Studying\CY-Workspace\MonoScene-master> python monoscene/scripts/eval_monoscene.py dataset=kitti kitti_root=$KITTI_ROOT kitti_preprocess_root=$KITTI_PREPROCESS  n_gpus=1 batch_size=
1
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
n_relations 4
Using cache found in C:\Users\DELL/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
Traceback (most recent call last):
  File "monoscene/scripts/eval_monoscene.py", line 71, in main
    data_module.setup()
  File "F:\anaconda\envs\monoscene\lib\site-packages\pytorch_lightning\core\datamodule.py", line 440, in wrapped_fn
    fn(*args, **kwargs)
  File "F:\Studying\CY-Workspace\MonoScene-master\monoscene\scripts/../..\monoscene\data\semantic_kitti\kitti_dm.py", line 34, in setup
    color_jitter=(0.4, 0.4, 0.4),
  File "F:\Studying\CY-Workspace\MonoScene-master\monoscene\scripts/../..\monoscene\data\semantic_kitti\kitti_dataset.py", line 60, in __init__
    os.path.join(self.root, "dataset", "sequences", sequence, "calib.txt")
  File "F:\Studying\CY-Workspace\MonoScene-master\monoscene\scripts/../..\monoscene\data\semantic_kitti\kitti_dataset.py", line 193, in read_calib
    with open(calib_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset\\sequences\\00\\calib.txt'

**Comment by anhquancao** [comment]
Hi @cyaccpect,
Please take a look at the dataset preparation section
https://github.com/cv-rits/MonoScene#semantickitti
`The KITTI Odometry Benchmark calibration data (Download odometry data set (calibration files, 1 MB)) and the RGB images (Download odometry data set (color, 65 GB)) from [KITTI Odometry website](http://www.cvlibs.net/datasets/kitti/eval_odometry.php).
`

**Comment by cyaccpect** [comment]
whether something go wrong with  environment variable? I have downloaded the dataset above 

![image](https://user-images.githubusercontent.com/85442705/158205973-ef3b7ef8-8fd0-4037-8e24-d65b2ac76a4b.png)

![image](https://user-images.githubusercontent.com/85442705/158206765-d2bb261d-43d6-4089-8035-352497f4d648.png)

**Comment by anhquancao** [comment]
You need to put them under the same folder instead of extracting them to 3 different folders.

**Comment by cyaccpect** [comment]
Was sorry very much must disturb you once more，I have tried to change my folder , But the problem still exists.
![image](https://user-images.githubusercontent.com/85442705/158803934-6f04b92d-9f01-4992-8dbb-9f64b2051ef6.png)

**Comment by anhquancao** [comment]
No worry! The folder structure of the semantic kitti dataset should be as follows:
![Screenshot from 2022-03-17 17-28-57](https://user-images.githubusercontent.com/9668858/158848036-daa1254d-dd4a-4832-accd-25caff496a11.jpg)

**Comment by cyaccpect** [comment]
Thank u very much, what's the folder "velodyne" and "labels",  and how to deal with "image_3". 
Furthermore,  I'm not clear very much about the path below:
![image](https://user-images.githubusercontent.com/85442705/158949353-1ccd0677-424d-488a-855d-dd6214ed9af3.png)

**Comment by anhquancao** [comment]
I think you don't need folder "velodyne". 
Folder "labels" contains the SSC ground-truth downloaded from the semantic kitti SSC dataset.
I don't use "image_3" so you can ignore it.

"/path/to/kitti/preprocess/folder" is just a folder that you create to store the preprocessed data later.

**Comment by cyaccpect** [comment]
1.The problem still exists
![image](https://user-images.githubusercontent.com/85442705/159009375-779e015f-217c-4787-8611-a35f4251b963.png)
2.
![image](https://user-images.githubusercontent.com/85442705/159009886-0ce3e23b-87c8-49d2-b0ae-cf25f25067ec.png)

PS F:\Studying\CY-Workspace\MonoScene-master>  python monoscene/data/semantic_kitti/preprocess.py kitti_root=$KITTI_ROOT kitti_preprocess_root=$KITTI_PREPROCESS
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]

**Comment by anhquancao** [comment]
What are the values of $KITTI_ROOT and $KITTI_PREPROCESS i.e. by running the command: "echo $KITTI_ROOT"?
