### ISSUE TITLE
Visualization tool

### ISSUE THREAD

**Issue by ngoductuanlhp** [cv-rits/MonoScene#16]
Hi @anhquancao , your .gif demo is very interesting. Could you share the script to generate this demo? 

Thank you very much.

**Comment by anhquancao** [comment]
Hi @ngoductuanlhp, to generate the demo, I first generate each frame with the same viewpoint, then use the video editor e.g. davinci resolve tool to assemble the frames into a video.

**Comment by anhquancao** [comment]
You can take a look at the following codes:
[1] https://github.com/anhquancao/SSC2d-[2] visualize/blob/6b07bdb310cd24c48c08c2fa5cac8c98bccee512/lib/helper_kitti.py#L12
https://github.com/anhquancao/SSC2d-visualize/blob/master/kitti_vis_pred.py#L94

To generate the code to change the camera viewpoint as in [1], you need to follow the following tutorial:
https://docs.enthought.com/mayavi/mayavi/application.html#recording-mayavi-actions-to-a-script

**Comment by ngoductuanlhp** [comment]
Thanks a lot. Now I can get the same camera viewpoint in different frames.

**Comment by kebijuelun** [comment]
> [1] [https://github.com/anhquancao/SSC2d-[2]](https://github.com/anhquancao/SSC2d-%5B2%5D) visualize/blob/6b07bdb310cd24c48c08c2fa5cac8c98bccee512/lib/helper_kitti.py#L12
> https://github.com/anhquancao/SSC2d-visualize/blob/master/kitti_vis_pred.py#L94

Thanks for the wonderful work, these links failed to open, could you please udpate the links?

best

**Comment by kebijuelun** [comment]
> > [1] [https://github.com/anhquancao/SSC2d-[2]](https://github.com/anhquancao/SSC2d-%5B2%5D) visualize/blob/6b07bdb310cd24c48c08c2fa5cac8c98bccee512/lib/helper_kitti.py#L12
> > https://github.com/anhquancao/SSC2d-visualize/blob/master/kitti_vis_pred.py#L94
> 
> Thanks for the wonderful work, these links failed to open, could you please udpate the links?
> 
> best


I have found out  the way to use generated scripts, such like:

```
from mayavi.api import Engine
engine = Engine()
engine.start()
scene = engine.scenes[0]
    scene.scene.camera.position = [-60.58825795977401, 21.157014981545093, 50.718208823185556]
    scene.scene.camera.focal_point = [26.360000076238066, 25.800000071525574, 1.9100000262260437]
    scene.scene.camera.view_angle = 30.0
    scene.scene.camera.view_up = [0.490062445498992, -0.015325179458712417, 0.8715526021911161]
    scene.scene.camera.clipping_range = [49.30213893945163, 161.93546276257854]
    scene.scene.camera.compute_view_plane_normal()
    scene.scene.render()
```

**Comment by anhquancao** [comment]
You can also check my post here
https://anhquancao.github.io/blog/2022/how-to-define-viewpoint-programmatically-in-mayavi/
