### ISSUE TITLE
about Ablation studies

### ISSUE THREAD

**Issue by DipDipPotatoChips** [cv-rits/MonoScene#17]
Can this code do some ablation studies？

**Comment by anhquancao** [comment]
Hi @DipDipPotatoChips
You can ablate MonoScene by changing the input parameters in the following line
https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/monoscene.py#L17

**Comment by DipDipPotatoChips** [comment]
> Hi @DipDipPotatoChips You can ablate MonoScene by changing the input parameters in the following line https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/monoscene.py#L17

thanks for your reply,but I can't find the  FLoSP and the 3D CRP mentioned in the  papers.So if I want to test it, I have to change the code, right？

**Comment by anhquancao** [comment]
You only need to change the parameter in the config:
https://github.com/cv-rits/MonoScene/blob/master/monoscene/config/monoscene.yaml

```
project_1_2: true #use features at scale 1:2
project_1_4: true #use features at scale 1:4
project_1_8: true #use features at scale 1:8
if all are false, you only feature at 1:1

relation_loss: true # supervise the 3D CRP

n_relations: 4 # The number of relations in the 3D CRP

fp_loss: true # turn on/off the frustum proportion loss
frustum_size: 8 # size of frustum in the fp_loss

```

**Comment by DipDipPotatoChips** [comment]
> relation_loss: true # supervise the 3D CRP

thanks！
