### ISSUE TITLE
Hidden Test set - Semantic Kitti dataset

### ISSUE THREAD

**Issue by BlarkLee** [cv-rits/MonoScene#19]
Hi, thanks for your amazing wonderful work. For the semantic kitti data preparation, your code only contains 00-10 sequences which contain training and val splits, in your paper you mentioned the testing split is "hidden split" which is on "online server"? Could you please tell me how to prepare the testing split (11-21 sequences), it looks that there is no .label and .invalid files for these sequences.

Thanks!

**Comment by anhquancao** [comment]
Hi @BlarkLee, Thanks for your interest in our work!
Indeed, there is no label available for the test sequences. To get the test performance you need to perform inference on the test dataset, save the output, then submit it to this competition.
https://competitions.codalab.org/competitions/22037#learn_the_details-participate

You can get the test dataset code from the KittiDataModule here
https://github.com/cv-rits/MonoScene/blob/master/monoscene/data/semantic_kitti/kitti_dm.py#L47

**Comment by BlarkLee** [comment]
I see! Thank you so much for the information!
