### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by DipDipPotatoChips** [cv-rits/MonoScene#2]
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruidong/workplace/MonoScene/trained_models/monoscene_kitti.ckpt'

the last printing of trainning is：
Epoch 29: 100%|\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 2325/2325 [1:06:52<00:00,  1.73s/it, loss=3.89, v_num=]

**Comment by DipDipPotatoChips** [comment]
and I find that the folder /trained_models is empty

**Comment by anhquancao** [comment]
Hello,
You need to download the pre-trained model here
https://github.com/cv-rits/MonoScene#pretrained-models

**Comment by DipDipPotatoChips** [comment]
> Hello, You need to download the pre-trained model here https://github.com/cv-rits/MonoScene#pretrained-models

So,should I retrain the model?

**Comment by anhquancao** [comment]
I don't understand. You only need to download the pre-trained checkpoints and put them in the folder /trained_models

**Comment by DipDipPotatoChips** [comment]
> I don't understand. You only need to download the pre-trained checkpoints and put them in the folder /trained_models

![image](https://user-images.githubusercontent.com/48906782/146902482-5f380adf-8dee-4758-9be1-e07108a02e77.png)

**Comment by anhquancao** [comment]
This is the evaluation results of the pre-trained models

**Comment by anhquancao** [comment]
Ah, I understand what do you mean. This is the MonoScene trained models, you don't need to retrain it.

**Comment by DipDipPotatoChips** [comment]
> Ah, I understand what do you mean. This is the MonoScene trained model, you don't need to retrain it. This is different from the pre-trained EfficientNet which is the pretrained 2D backbone and is required to train MonoScene from scratch.

The whole pre-train model?

**Comment by anhquancao** [comment]
Yes

**Comment by DipDipPotatoChips** [comment]
> Yes

how to train a model by myself to Evaluate?Can the codes save the model files?

**Comment by anhquancao** [comment]
Yes, the checkpoints are saved in $KITTI_LOG/checkpoints

**Comment by anhquancao** [comment]
Yes
