### ISSUE TITLE
Input Image

### ISSUE THREAD

**Issue by wenyihan4396** [cv-rits/MonoScene#22]
Hi Guys, 
I want to use a JPG image as input, can you opensource the code that exchange the image into PKL?
Thank you

**Comment by anhquancao** [comment]
Hi @wenyihan4396 ,

Thanks for your interest! 

The inference code can be found here
https://huggingface.co/spaces/CVPR/MonoScene/tree/main

Specifically, this file:
https://huggingface.co/spaces/CVPR/MonoScene/blob/main/app.py

Note that you need to modify the camera parameters in this function:
https://huggingface.co/spaces/CVPR/MonoScene/blob/main/helpers.py#L128

BR,
Anh-Quan

**Comment by wenyihan4396** [comment]
Hi Anh,
Thank you so much😊!
Best regards,
Yihan Wen

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Cao Anh ***@***.***>
发送时间: 2022年8月19日 15:43
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [cv-rits/MonoScene] Input Image (Issue #22)


Hi @wenyihan4396<https://github.com/wenyihan4396> ,

Thanks for your interest!

The inference code can be found here
https://huggingface.co/spaces/CVPR/MonoScene/tree/main

Specifically, this file:
https://huggingface.co/spaces/CVPR/MonoScene/blob/main/app.py

Note that you need to modify the camera parameters in this function:
https://huggingface.co/spaces/CVPR/MonoScene/blob/main/helpers.py#L128

BR,
Anh-Quan
