### ISSUE TITLE
capture photos with same viewport as input RGB image

### ISSUE THREAD

**Issue by wenyihan4396** [cv-rits/MonoScene#23]
Excuese me, I leverage NYU_vis_pred.py to visualize the pkl file and capture the 3D reconstruction scene
![image](https://user-images.githubusercontent.com/71435435/185769902-4bb660b1-6e59-4c63-8052-72929dad5f31.png)
 it's great to visualize the camera too. But it seems a mesh and can not take photos.
![image](https://user-images.githubusercontent.com/71435435/185769943-813b2d10-808d-4455-b795-1fd1b6ede5bc.png)

I want to take a photo with the same viewport as input RGB image, could you please tell me the reference code to realize my goal.
(希望通过相机参数拍摄与输入图片同视角的图片，请问有可参考的代码吗)
Best regards,
Yihan Wen

**Comment by anhquancao** [comment]
Hi @wenyihan4396,
For NYUv2, you should take a look at this line
https://github.com/cv-rits/MonoScene/blob/master/monoscene/data/NYU/nyu_dataset.py#L84
