### ISSUE TITLE
Can you help me in another paper?

### ISSUE THREAD

**Issue by WkangLiu** [cv-rits/MonoScene#24]
Hello！
Last year, when you reproduced the code SISC（https://github.com/OPEN-AIR-SUN/SISC）, you found a bug and solve it！
Now, I get the same problem too，can you tell me how to solve it ！
Thank you very much！

**Comment by anhquancao** [comment]
Hello,
it's really long time and I don't remember what was the problem but I found the code that I used. I hope it can help

```
#!/usr/bin/env python3

import logging
import numpy as np
import plyfile
import skimage.measure
import time
import os
from monoscene.models.monoscene2 import MonoScene2
from monoscene.data.semantic_kitti.kitti_dm import KittiDataModule
import click


def create_mesh(
    batch, model, filename, N=256, max_batch=64 ** 3, offset=None, scale=None
):
    start = time.time()
    ply_filename = filename
    voxel_origin = [0, 0, 0]
    voxel_size = 1.0

    model.eval()

    sdf_values = model.get_discrete_sdf(batch, (N, N, N//8))
    sdf_values = sdf_values.reshape((N, N, N//8))
    sdf_values = np.abs(sdf_values)    
    end = time.time()
    print("sampling takes: %f" % (end - start))

    convert_sdf_samples_to_ply(
        sdf_values,
        voxel_origin,
        voxel_size,
        ply_filename + ".ply",
        level=0.035,
        offset=offset,
        scale=scale,
    )


def convert_sdf_samples_to_ply(
    sdf_values,
    voxel_grid_origin,
    voxel_size,
    ply_filename_out,    
    level,
    label=None,
    offset=None,
    scale=None,
    ):
    '''
    Convert sdf samples to .ply with semantic infomation
    :param sdf_values: a numpy array of shape (n,n,n)
    :voxel_grid_origin: a list of three floats: the bottom, left, down origin of the voxel grid
    :voxel_size: float, the size of the voxels
    :ply_filename_out: string, path of the filename to save to
    This function adapted from: https://github.com/RobotLocomotion/spartan
    '''
    start_time = time.time()

    verts, faces, normals, values = np.zeros((0, 3)), np.zeros((0, 3)), np.zeros((0, 3)), np.zeros(0)
    try:
        verts, faces, normals, values = skimage.measure.marching_cubes(
            sdf_values, level=level, spacing=[voxel_size] * 3
        )
    except:
        pass

    # transform from voxel coordinates to camera coordinates
    # note x and y are flipped in the output of marching_cubes
    mesh_points = np.zeros_like(verts)
    mesh_points[:, 0] = voxel_grid_origin[0] + verts[:, 0]
    mesh_points[:, 1] = voxel_grid_origin[1] + verts[:, 1]
    mesh_points[:, 2] = voxel_grid_origin[2] + verts[:, 2]

    # apply additional offset and scale
    if scale is not None:
        mesh_points = mesh_points / scale
    if offset is not None:
        mesh_points = mesh_points - offset

    ##################
    if label is not None:
        label_points = np.transpose(label.nonzero())
        k_neigh = NearestNeighbors(n_neighbors=1)
        k_neigh.fit(label_points)
        indexes = k_neigh.kneighbors(mesh_points, return_distance=False).squeeze()

        co_label = label[tuple(np.transpose(label_points[indexes]))]
        classes = inv_map_lut[co_label]
        colors = color_map_lut[classes]
    ##################

    num_verts = verts.shape[0]
    num_faces = faces.shape[0]

    if label is not None:
        verts_tuple = np.zeros((num_verts,), dtype=[('x', 'f4'), ('y', 'f4'), ('z', 'f4'), ('red', 'u1'), ('green', 'u1'), ('blue', 'u1')])
        for i in range(0, num_verts):
            verts_tuple[i] = tuple(np.concatenate((mesh_points[i, :], colors[i, :]), axis=-1))
    else:
        verts_tuple = np.zeros((num_verts,), dtype=[("x", "f4"), ("y", "f4"), ("z", "f4")])
        for i in range(0, num_verts):
            verts_tuple[i] = tuple(mesh_points[i, :])

    faces_building = []
    for i in range(0, num_faces):
        faces_building.append(((faces[i, :].tolist(),)))
    faces_tuple = np.array(faces_building, dtype=[('vertex_indices', 'i4', (3,))])

    el_verts = plyfile.PlyElement.describe(verts_tuple, 'vertex')
    el_faces = plyfile.PlyElement.describe(faces_tuple, 'face')

    ply_data = plyfile.PlyData([el_verts, el_faces])
    logging.debug('saving mesh to %s' % (ply_filename_out))
    ply_data.write(ply_filename_out)

    logging.debug(
        'converting to ply format and writing to file took {} s'.format(
            time.time() - start_time
        )
    )


@click.command()
@click.option('--root', default="/gpfswork/rech/kvd/uyl37fq/data/semantic_kitti", help='path to dataset folder')
@click.option('--preprocess_root', default="/gpfsscratch/rech/kvd/uyl37fq/monoscene_preprocess/kitti", help='path to preprocess folder')
@click.option('--scale', default=1, help='drawing scale')
def main(root, preprocess_root, scale):
    data_module = KittiDataModule(
        root=root,
        preprocess_root=preprocess_root,                
        batch_size=1,
        num_workers=3,
    )    
    data_module.setup()
    model = MonoScene2.load_from_checkpoint("...")
    model.cuda()
    model.eval()
    dataloader = data_module.val_dataloader()

    
    cnt = 0
    for batch in dataloader:               
        frame_id  = batch['frame_id'][0]
        filename = os.path.join("...", frame_id)
        batch['img'] = batch['img'].cuda() 
        create_mesh(batch, model, filename, N=256 // scale)
        cnt += 1
        if cnt == 10:
            break

if __name__ == "__main__":
    main()
```

**Comment by WkangLiu** [comment]
First of all, thank you very much for your reply.
Unfortunately,&nbsp; this part of the code is not part of the SISC source code and still has problems after I modified it.
If y 发送 ou can search the source code of SISC, can you send me a copy? Thank you very much! If not, again, thank you for your help！

Also, congratulations, your article was included in cvpr2022




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cao Anh ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cv-rits/MonoScene] Can you help me in another paper? (Issue #24)





 
Hello,
 it's really long time and I don't remember what was the problem but I found the code that I used. I hope it can help
 #!/usr/bin/env python3 import logging import numpy as np import plyfile import skimage.measure import time import os from monoscene.models.monoscene2 import MonoScene2 from monoscene.data.semantic_kitti.kitti_dm import KittiDataModule import click def create_mesh(     batch, model, filename, N=256, max_batch=64 ** 3, offset=None, scale=None ):     start = time.time()     ply_filename = filename     voxel_origin = [0, 0, 0]     voxel_size = 1.0     model.eval()     sdf_values = model.get_discrete_sdf(batch, (N, N, N//8))     sdf_values = sdf_values.reshape((N, N, N//8))     sdf_values = np.abs(sdf_values)         end = time.time()     print("sampling takes: %f" % (end - start))     convert_sdf_samples_to_ply(         sdf_values,         voxel_origin,         voxel_size,         ply_filename + ".ply",         level=0.035,         offset=offset,         scale=scale,     ) def convert_sdf_samples_to_ply(     sdf_values,     voxel_grid_origin,     voxel_size,     ply_filename_out,         level,     label=None,     offset=None,     scale=None,     ):     '''     Convert sdf samples to .ply with semantic infomation     :param sdf_values: a numpy array of shape (n,n,n)     :voxel_grid_origin: a list of three floats: the bottom, left, down origin of the voxel grid     :voxel_size: float, the size of the voxels     :ply_filename_out: string, path of the filename to save to     This function adapted from: https://github.com/RobotLocomotion/spartan     '''     start_time = time.time()     verts, faces, normals, values = np.zeros((0, 3)), np.zeros((0, 3)), np.zeros((0, 3)), np.zeros(0)     try:         verts, faces, normals, values = skimage.measure.marching_cubes(             sdf_values, level=level, spacing=[voxel_size] * 3         )     except:         pass     # transform from voxel coordinates to camera coordinates     # note x and y are flipped in the output of marching_cubes     mesh_points = np.zeros_like(verts)     mesh_points[:, 0] = voxel_grid_origin[0] + verts[:, 0]     mesh_points[:, 1] = voxel_grid_origin[1] + verts[:, 1]     mesh_points[:, 2] = voxel_grid_origin[2] + verts[:, 2]     # apply additional offset and scale     if scale is not None:         mesh_points = mesh_points / scale     if offset is not None:         mesh_points = mesh_points - offset     ##################     if label is not None:         label_points = np.transpose(label.nonzero())         k_neigh = NearestNeighbors(n_neighbors=1)         k_neigh.fit(label_points)         indexes = k_neigh.kneighbors(mesh_points, return_distance=False).squeeze()         co_label = label[tuple(np.transpose(label_points[indexes]))]         classes = inv_map_lut[co_label]         colors = color_map_lut[classes]     ##################     num_verts = verts.shape[0]     num_faces = faces.shape[0]     if label is not None:         verts_tuple = np.zeros((num_verts,), dtype=[('x', 'f4'), ('y', 'f4'), ('z', 'f4'), ('red', 'u1'), ('green', 'u1'), ('blue', 'u1')])         for i in range(0, num_verts):             verts_tuple[i] = tuple(np.concatenate((mesh_points[i, :], colors[i, :]), axis=-1))     else:         verts_tuple = np.zeros((num_verts,), dtype=[("x", "f4"), ("y", "f4"), ("z", "f4")])         for i in range(0, num_verts):             verts_tuple[i] = tuple(mesh_points[i, :])     faces_building = []     for i in range(0, num_faces):         faces_building.append(((faces[i, :].tolist(),)))     faces_tuple = np.array(faces_building, dtype=[('vertex_indices', 'i4', (3,))])     el_verts = plyfile.PlyElement.describe(verts_tuple, 'vertex')     el_faces = plyfile.PlyElement.describe(faces_tuple, 'face')     ply_data = plyfile.PlyData([el_verts, el_faces])     logging.debug('saving mesh to %s' % (ply_filename_out))     ply_data.write(ply_filename_out)     logging.debug(         'converting to ply format and writing to file took {} s'.format(             time.time() - start_time         )     ) @click.command() @click.option('--root', default="/gpfswork/rech/kvd/uyl37fq/data/semantic_kitti", help='path to dataset folder') @click.option('--preprocess_root', default="/gpfsscratch/rech/kvd/uyl37fq/monoscene_preprocess/kitti", help='path to preprocess folder') @click.option('--scale', default=1, help='drawing scale') def main(root, preprocess_root, scale):     data_module = KittiDataModule(         root=root,         preprocess_root=preprocess_root,                         batch_size=1,         num_workers=3,     )         data_module.setup()     model = MonoScene2.load_from_checkpoint("...")     model.cuda()     model.eval()     dataloader = data_module.val_dataloader()          cnt = 0     for batch in dataloader:                        frame_id  = batch['frame_id'][0]         filename = os.path.join("...", frame_id)         batch['img'] = batch['img'].cuda()          create_mesh(batch, model, filename, N=256 // scale)         cnt += 1         if cnt == 10:             break if __name__ == "__main__":     main()

**Comment by anhquancao** [comment]
Hello, 
Thanks! The only codes I use from them is this code to generate the mesh. Btw, what is your problem?

**Comment by WkangLiu** [comment]
hello,it's that
i'm chinese ,if you also ,you can speak chinese!

Traceback (most recent call last):
&nbsp; File "main_ssc_a.py", line 1248, in <module&gt;
&nbsp;&nbsp;&nbsp; main()
&nbsp; File "main_ssc_a.py", line 1244, in main
&nbsp;&nbsp;&nbsp; visualize(opt, config, expr_path)
&nbsp; File "main_ssc_a.py", line 1174, in visualize
&nbsp;&nbsp;&nbsp; visualize_pipeline(D_Seg=D_Seg, D_SSC=D_SSC, \
&nbsp; File "main_ssc_a.py", line 1122, in visualize_pipeline
&nbsp;&nbsp;&nbsp; iou_out = evals.scene_save_ssc_a(G_siren, shape_out[0], class_out, raw, label, mask, config, model_dir, indices[0])
&nbsp; File "/home/SISC/evals.py", line 353, in scene_save_ssc_a
&nbsp;&nbsp;&nbsp; convert_sdf_samples_to_ply(
&nbsp; File "/home/SISC/evals.py", line 589, in convert_sdf_samples_to_ply
&nbsp;&nbsp;&nbsp; indexes = k_neigh.kneighbors(mesh_points, return_distance=False).squeeze()
&nbsp; File "/opt/conda/lib/python3.8/site-packages/sklearn/neighbors/_base.py", line 670, in kneighbors
&nbsp;&nbsp;&nbsp; X = check_array(X, accept_sparse='csr')
&nbsp; File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
&nbsp;&nbsp;&nbsp; return f(*args, **kwargs)
&nbsp; File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 669, in check_array
&nbsp;&nbsp;&nbsp; raise ValueError("Found array with %d sample(s) (shape=%s) while a"
ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required.
Killing subprocess 258578
Traceback (most recent call last):
&nbsp; File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
&nbsp;&nbsp;&nbsp; return _run_code(code, main_globals, None,
&nbsp; File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
&nbsp;&nbsp;&nbsp; exec(code, run_globals)
&nbsp; File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module&gt;
&nbsp;&nbsp;&nbsp; main()
&nbsp; File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
&nbsp;&nbsp;&nbsp; sigkill_handler(signal.SIGTERM, None)&nbsp; # not coming back
&nbsp; File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
&nbsp;&nbsp;&nbsp; raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'main_ssc_a.py', '--local_rank=0', '--task=visualize', '--experiment_name=test-vis']' returned non-zero exit status 1.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cao Anh ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 下午3:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cv-rits/MonoScene] Can you help me in another paper? (Issue #24)





 
Hello,
 Thanks! The only codes I use from them is this code to generate the mesh. Btw, what is your problem?

**Comment by anhquancao** [comment]
Hi! I am not Chinese, this seems to be errors in their code, I think you should ask them. 
Maybe you already known, you can try to use pdb.set_trace() to debug the variables.

**Comment by WkangLiu** [comment]
hi, Thank you very very very much!!!!





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cao Anh ***@***.***&gt;; 
发送时间: 2022年9月23日(星期五) 下午3:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cv-rits/MonoScene] Can you help me in another paper? (Issue #24)





 
Hi! I am not Chinese, this seems to be errors in their code, I think you should ask them.
 Maybe you already known, you can try to use pdb.set_trace() to debug the variables.

**Comment by anhquancao** [comment]
You're welcome. Sorry for not being able to help!

**Comment by WkangLiu** [comment]
Thanks for the help from across the Atlantic！
