### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by jiachenglihxl** [cv-rits/MonoScene#25]
Hi, very impressive work. When I try to train NYU dataset, by using following cmd:

python monoscene/scripts/train_monoscene.py     dataset=NYU     NYU_root=$NYU_ROOT     NYU_preprocess_root=$NYU_PREPROCESS     logdir=$NYU_LOG     n_gpus=1 batch_size=2

I get this:

CUDA out of memory. Tried to allocate 100.00 MiB (GPU 0; 15.73 GiB total capacity; 12.49 GiB already allocated; 93.81 MiB free; 12.96 GiB reserved in total by PyTorch)

My GPU is RTX 5000，which have 16GB Memory. I tried batch_size=1, but still the same.

Do you have any suggestion about my problem? Thanks.

**Comment by anhquancao** [comment]
Hi @jiachenglihxl,
Thank you for your intrest!. To reduce the memory consumption you can try the following option:
1. Scale down input image: you need to adapt the projection matrix also
2. Use smaller 2D backbone by chaning the [basemodel_name and num_features](https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet2d.py#L177)
The pretrained model name is [here](https://github.com/rwightman/gen-efficientnet-pytorch#ported-weights). You can try the efficientnet B5.
3. Reduce the [feature dimenation of the 3D network](https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet3d_nyu.py#L32)
4. Try to disable or reduce the size of  [the context prior](https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet3d_nyu.py#L61)

**Comment by jiachenglihxl** [comment]
Thanks to help. I will try~
