### ISSUE TITLE
train log file

### ISSUE THREAD

**Issue by Anonymous-N** [cv-rits/MonoScene#28]
Dear authors, thanks for your great works! I‘d like to know if it is convenient for you to provide log files during training, because I cannot reproduce the same results at present, I want to refer to your logs for comparison
thank you

**Comment by anhquancao** [comment]
Hi @Anonymous-N, unfortunately I didn't keep the log file. Can you show me your training metrics e.g. training and validation IoU, mIoU?

**Comment by Anonymous-N** [comment]
Thank you for your reply! I used 2 3090GPUS to train the model and got the best val mIoU=0.11342  at epoch 26. Is this a normal value?
Train iou is 0.528 and val iou is about 0.365
And I note that the val loss keeps rising gradually from 8.6 to 12 during training. Why this happened?

**Comment by anhquancao** [comment]
Your training is going well. These numbers are almost the same as what I got. You can check Table 8 in supp. 
![image](https://user-images.githubusercontent.com/9668858/196927584-4815f4c3-ed87-4838-b6e1-6d77637006a7.png)

I also see the val loss increasing but the metrics are still improving.

**Comment by Anonymous-N** [comment]
Thanks for such a quick reply and your wonderful work!
Additional, If there is any explanation on the increasing loss I'd like to be informed

**Comment by anhquancao** [comment]
No problem! Unfortunately, I haven't investigate this but I also saw this issue in SSC task with 3D input.
