### ISSUE TITLE
About augmentation technique

### ISSUE THREAD

**Issue by weiyithu** [cv-rits/MonoScene#29]
Dear author:
  Do you use any augmentation techniques in this work, such as random brightness of images?

**Comment by anhquancao** [comment]
Hi @weiyithu, I used color jitter and flip image left right, you can check the code here
https://github.com/cv-rits/MonoScene/blob/master/monoscene/data/semantic_kitti/kitti_dm.py#L33

**Comment by weiyithu** [comment]
Get it.  Thanks a lot!
