### ISSUE TITLE
about visualization

### ISSUE THREAD

**Issue by DipDipPotatoChips** [cv-rits/MonoScene#3]
(monoscene) ruidong@ubuntu-X299-UD4-Pro:~/workplace/MonoScene$ python monoscene/scripts/visualization/kitti_vis_pred.py +file=/home/ruidong/workplace/MonoScene/outputs/kitti/08/000000.pkl +dataset=kitt
monoscene/scripts/visualization/kitti_vis_pred.py:23: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  coords_grid = coords_grid.astype(np.float)
Traceback (most recent call last):
  File "monoscene/scripts/visualization/kitti_vis_pred.py", line 196, in main
    d=7,
  File "monoscene/scripts/visualization/kitti_vis_pred.py", line 75, in draw
    grid_coords = np.vstack([grid_coords.T, voxels.reshape(-1)]).T
AttributeError: 'tuple' object has no attribute 'T'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by DipDipPotatoChips** [comment]
Oh,yes.
if failed to install mayavi using
`pip install mayavi`
failed about building wheel for mayavi.
I found it seems that the version of vtk is too new with 9.1,I recommand to do this if using python3.7:
`pip install PyQt5`
`pip install VTK==8.1.2`
`pip install mayavi`

**Comment by anhquancao** [comment]
So did you solve the error above?

**Comment by DipDipPotatoChips** [comment]
> So did you solve the error above?

No,I solve the problem of installing for mayvi before vasualization

**Comment by anhquancao** [comment]
Could you change the following line like this?
https://github.com/cv-rits/MonoScene/blob/master/monoscene/scripts/visualization/kitti_vis_pred.py#L32

**Comment by DipDipPotatoChips** [comment]
`git pull`
ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 542
vtkXOpenGLRenderWindow (0x5567b357f750): GLX not found.  Aborting.

now I'm trying to solve

**Comment by DipDipPotatoChips** [comment]
> `git pull` ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 542 vtkXOpenGLRenderWindow (0x5567b357f750): GLX not found. Aborting.
> 
> now I'm trying to solve

It seemed that I have sovled that by running  the command of visualization on the local computer instead of vnc.
The problem arises from the xstartup,I believe.

**Comment by DipDipPotatoChips** [comment]
> Could you change the following line like this? https://github.com/cv-rits/MonoScene/blob/master/monoscene/scripts/visualization/kitti_vis_pred.py#L32

It works.thanks for your patience!

![image](https://user-images.githubusercontent.com/48906782/146926254-518c0c30-e75b-4d7d-bf4d-7bc1481e05e7.png)

**Comment by anhquancao** [comment]
Awesome! I am pleased to hear that

**Comment by azuryl** [comment]
> Oh,yes. if failed to install mayavi using `pip install mayavi` failed about building wheel for mayavi. I found it seems that the version of vtk is too new with 9.1,I recommand to do this if using python3.7: `pip install PyQt5` `pip install VTK==8.1.2` `pip install mayavi`
according to @anhquancao guide there is a core dump when run NYU predict.
I fixed it by
conda install -c anaconda mayavi
pip install omegaconf
pip install hydra-core
pip install numba==0.53
downgrading TBB to version 2020.2 with conda install -c bioconda tbb=2020.2
