### ISSUE TITLE
How to train my own datasets?

### ISSUE THREAD

**Issue by lulianLiu** [cv-rits/MonoScene#30]
Dear author, I want to know how train my own datasets?

**Comment by anhquancao** [comment]
Hi @lulianLiu,
Can you be more specific about your dataset? I recommend:
1. Adapt [this file](https://github.com/cv-rits/MonoScene/blob/master/monoscene/data/semantic_kitti/preprocess.py) to generate 3D ground truth at 1:8 resolution
2. Modile [kitti dataset loader](https://github.com/cv-rits/MonoScene/blob/master/monoscene/data/semantic_kitti/kitti_dataset.py#L69) with your camera intrinsic parameter. If you predict the 3D scene in the camera coordinate then T_velo_2_cam can be set to np.eye(4)

**Comment by lulianLiu** [comment]
> Hi @lulianLiu, You can follow these steps to write the dataloader for your dataset:
> 
>     1. Adapt [this file](https://github.com/cv-rits/MonoScene/blob/master/monoscene/data/semantic_kitti/preprocess.py) to generate 3D ground truth at 1:8 resolution
> 
>     2. Modile [kitti dataset loader](https://github.com/cv-rits/MonoScene/blob/master/monoscene/data/semantic_kitti/kitti_dataset.py#L69) with your camera intrinsic parameter. If you predict the 3D scene in the camera coordinate then T_velo_2_cam can be set to np.eye(4)
> 
>     3. You might need to modify [voxel_origin and scene size](https://github.com/cv-rits/MonoScene/blob/master/monoscene/data/semantic_kitti/kitti_dataset.py#L41). This define the area of the scene you want to predict
Dear author,  if I train  by the kitti data. I need to download follow two data?Can I download the kitti(700M) to train and modile the data to make my own data?

**Comment by anhquancao** [comment]
You need the calibaration files and the RGB images which are not in the 700Mb data.

**Comment by anhquancao** [comment]
Sorry, I don't have the smaller dataset. You need to calibration file for the camera intrinsics and 3D ground truth to train

**Comment by AgentEXPL** [comment]
Hi, @anhquancao How to obtain the .pkl and .bin files from the original NYU dataset?
