### ISSUE TITLE
latex figure

### ISSUE THREAD

**Issue by luzonghao1** [cv-rits/MonoScene#35]
Hello, how did the segmentation image in the paper add the color squares? Can you give me a latex code? thanks

**Comment by anhquancao** [comment]
Hi @luzonghao1, you can download the latex source here
https://arxiv.org/format/2112.00726

**Comment by luzonghao1** [comment]
thank you very much

**Comment by luzonghao1** [comment]
> Hi @luzonghao1, you can download the latex source here https://arxiv.org/format/2112.00726

thank you very much
