### ISSUE TITLE
How to draw the triangles in the visualization?

### ISSUE THREAD

**Issue by rockywind** [cv-rits/MonoScene#36]
Hi,
I am confusing this operation because it is not the transformation from  image coordination to camera coordination in the [line](https://github.com/cv-rits/MonoScene/blob/e9ac5832d5b1ed59899f80b61b7b80495c823f41/monoscene/scripts/visualization/kitti_vis_pred.py#L46) 
![image](https://user-images.githubusercontent.com/14838781/200494584-435a2855-b476-4e10-8ed8-640af80f3f43.png)

**Comment by anhquancao** [comment]
Hi @rockywind, I draw the triangle directly in the camera coordinates space using the focal length f extracted from the projection matrix. There is no need of any transformation from 2D to 3D.
