### ISSUE TITLE
How to fixed the grid size in the mayavi?

### ISSUE THREAD

**Issue by rockywind** [cv-rits/MonoScene#37]
Dear, author,
I found that if only one object is in the scene, the grid size is larger than the two objects in the scene.
My code is below.
```
    # Compute the voxels coordinates
    grid_coords = get_grid_coords(
        [voxels.shape[0], voxels.shape[1], voxels.shape[2]], voxel_size
    )

    # Attach the predicted class to every voxel

    grid_coords = np.vstack([grid_coords.T, voxels.reshape(-1)]).T


    # Remove empty and unknown voxels
    occupied_voxels = grid_coords[(grid_coords[:, 3] > 0) & (grid_coords[:, 3] < 255)]

    # Draw occupied voxels
    plt_plot = mlab.points3d(
        occupied_voxels[:, 0],
        occupied_voxels[:, 1],
        occupied_voxels[:, 2],
        occupied_voxels[:, 3],
        colormap="viridis",
        scale_factor=voxel_size - 0.5 * voxel_size,
        mode="cube",
        opacity=1.0,
        vmin=0,
        vmax=12,
    )

    colors = np.array(
        [
            [100, 150, 245, 255],
            [100, 230, 245, 255],
            [30, 60, 150, 255],
            [80, 30, 180, 255],
            [100, 80, 250, 255],
            [255, 30, 30, 255],
            [255, 40, 200, 255],
            [150, 30, 90, 255],
            [255, 0, 255, 255],
            [255, 150, 255, 255],
            [75, 0, 75, 255],
            [175, 0, 75, 255],
            [255, 200, 0, 255],
            [255, 120, 50, 255],
            [0, 175, 0, 255],
            [135, 60, 0, 255],
            [150, 240, 80, 255],
            [255, 240, 150, 255],
            [255, 0, 0, 255],
        ]
    ).astype(np.uint8)

    plt_plot.glyph.scale_mode = "scale_by_vector"

    plt_plot.module_manager.scalar_lut_manager.lut.table = colors

    mlab.show()
    mlab.savefig(filename=save_path)
```
![image](https://user-images.githubusercontent.com/14838781/201681979-575c550f-015d-4dfa-b19b-2f196dcdf88d.png)
![image](https://user-images.githubusercontent.com/14838781/201682126-bb785412-2ebf-47ee-a4e4-db599bd9867f.png)

**Comment by anhquancao** [comment]
Hi @rockywind, I don't understand your problem?
The grid_size is defined here:
```
# Compute the voxels coordinates
  grid_coords = get_grid_coords(
      [voxels.shape[0], voxels.shape[1], voxels.shape[2]], voxel_size
  )
```
It doesn't depend on the objects.

**Comment by rockywind** [comment]
Dear author,
The grid size is 0.25. But some objects grid size  drawed in the picture is larger than anthor. I am confused.

**Comment by rockywind** [comment]
Dear author,
Just like two pictures below.
Their grid size is 0.25. But the first one picture's grid size looked larger the the sencond one.
![image](https://user-images.githubusercontent.com/14838781/201687581-0fbc9775-95f5-455d-8808-7d97bb5a510b.png)
![image](https://user-images.githubusercontent.com/14838781/201687629-8c62fd97-8da9-4768-a0ed-4aeaf9c8572b.png)

**Comment by rockywind** [comment]
The voxel's shape is 400 * 400 * 25 in all scenes, and the voxel size is 0.25.
I can't find any scale factor in the code.
I found that the grid size is smaller with the object's number increase.
![image](https://user-images.githubusercontent.com/14838781/201730060-e1b37930-3f48-4117-ae44-ff90b9f94b73.png)
![image](https://user-images.githubusercontent.com/14838781/201730140-e64fa137-c59c-4ba2-a8e2-f9628ee0e0aa.png)

**Comment by anhquancao** [comment]
Did you set the viewpoint? You can follow this post to set the mayavi viewpoint
https://anhquancao.github.io/blog/2022/how-to-define-viewpoint-programmatically-in-mayavi/
