### ISSUE TITLE
about test with model file trained by myself

### ISSUE THREAD

**Issue by DipDipPotatoChips** [cv-rits/MonoScene#4]
this is the output with pre-train model:
![3ac5d9b9d7568fdbe8b939975ece344](https://user-images.githubusercontent.com/48906782/147060598-1b7aae66-2398-40a4-b9e2-79b34b0e36df.png)
this is the output with model trained by myself:
![34432caeb48bf41e246bc68f4773791](https://user-images.githubusercontent.com/48906782/147060725-fa411af9-f89f-48f7-9634-14290de87bf0.png)

remember that,in another issue the GPU is not enough and you told me to change the feature from 64 to 32 while training
https://github.com/cv-rits/MonoScene/issues/1#issuecomment-997396449

this feature is different from batchsize,right?

**Comment by anhquancao** [comment]
It is the feature dimension of the 3D network. You can take a look at this file.
https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet3d_kitti.py#L25

**Comment by DipDipPotatoChips** [comment]
> It is the feature dimension of the 3D network. You can take a look at this file. https://github.com/cv-rits/MonoScene/blob/master/monoscene/models/unet3d_kitti.py#L25

Can the batch be reduced？Did a batchsize corresponds to a frame of image?

**Comment by anhquancao** [comment]
Since 1 item can only be fitted in 1 GPU, batch size = number of GPUs. So it's not possible to save memory by reducing batch size.
