### ISSUE TITLE
Issue with HuggingFace space with NYU dataset

### ISSUE THREAD

**Issue by samraul** [cv-rits/MonoScene#86]
Hi @anhquancao,

I have been trying to test the NYU dataset results using the [HuggingFace space](https://huggingface.co/spaces/CVPR/MonoScene/tree/main). Following the information in other issues, I have implemented the following changes:

1. Load nyu.ckpt
```
model = MonoScene.load_from_checkpoint(
        "monoscene_nyu.ckpt",
        dataset="NYU",
        n_classes=12,
        feature = 200,
        project_scale = 1,
        full_scene_size = (60, 36, 60)
    )
img_W, img_H = 640, 480
```

2. Provide projections in `batch` from [NYU dataset values](https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/NYU/nyu_dataset.py#L36)
```
for scale_3d in scale_3ds:
    voxel_size = 0.08
    scene_size = (4.8, 4.8, 2.88)
    img_W = 640
    img_H = 480
    cam_k = np.array([[518.8579, 0, 320], [0, 518.8579, 240], [0, 0, 1]])
    vox_origin, cam_pose, _ = _read_rle('nyu_test/NYU1021_0000.bin')
    ... vox2pix(...)
```

3. Removed pooling (it seem necessary only for kitti?)
```
# pred = majority_pooling(pred, k_size=2)
```

It does process the image, however the output does not seem correct. Looking at the output, is there anything obvious that I am missing?
<kbd><img width="800" src="https://github.com/astra-vision/MonoScene/assets/73083942/5b559707-835e-41ea-bedd-bfee00570cb5"/></kbd>

Otherwise I can switch to `generate_output.py` if that's an easier approach.

Thank you!

**Comment by samraul** [comment]
This is the output with `pred = majority_pooling(pred, k_size=1)`:
<kbd><img width="600" src="https://github.com/astra-vision/MonoScene/assets/73083942/e6a659d2-88a9-4fd2-bfc9-78e3df67f2f9"/></kbd>

**Comment by anhquancao** [comment]
Hi, the pretrained model designed for NYUv2 doesn't function as seamlessly as it does for KITTI. This is because the NYU scene reconstruction is based on world coordinates. To project the voxel onto the image, I use the camera pose, as detailed in [this section of the MonoScene code](https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/NYU/nyu_dataset.py#L68). It's important to note that the camera pose varies with each image.

To replicate something akin to the demo, you need to transform the voxels into the camera's coordinate system using the camera pose. Subsequently, retrain the model with these transformed voxels. This approach will eliminate the model's dependency on the camera pose during inference.

**Comment by samraul** [comment]
Thanks @anhquancao 

I wanted to apply this UI to analyze some samples of the NYU dataset, so I thought I would be able to convert the output to the proper format by updating the projections for each image (in this case I hardcoded the one image I was testing):

```python
    batch = get_NYU_projections() 
    #batch = get_projections(img_W, img_H)
    batch["img"] = img
```

with
```python
def get_NYU_projections():
    scale_3ds = [1, 2]
    data = {}
    for scale_3d in scale_3ds:

        # https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/NYU/nyu_dataset.py#L36
        voxel_size = 0.08
        scene_size = (4.8, 4.8, 2.88)
        img_W = 640
        img_H = 480
        cam_k = np.array([[518.8579, 0, 320], [0, 518.8579, 240], [0, 0, 1]])
        vox_origin, cam_pose, _ = _read_rle('nyu_test/NYU1021_0000.bin')

        T_world_2_cam = np.linalg.inv(cam_pose)
        
        # compute the 3D-2D mapping
        projected_pix, fov_mask, pix_z = vox2pix(
            T_world_2_cam,
            cam_k,
            vox_origin,
            voxel_size * scale_3d,
            img_W,
            img_H,
            scene_size,
        )
        
        print(f"NYU fov_mask_{scale_3d} size = {fov_mask.shape}")

        data["projected_pix_{}".format(scale_3d)] = projected_pix
        data["pix_z_{}".format(scale_3d)] = pix_z
        data["fov_mask_{}".format(scale_3d)] = fov_mask 
    return data       
```

I was however able to check out the results via `generate_output.py` instead, without getting the gradio demo to work, so I am no longer trying to do so.

Thank you.

**Comment by anhquancao** [comment]
Great! I'm pleased to hear that. I close the issue then. Feel free to reopen it if you have another problem.
