### ISSUE TITLE
Inconsistent results of some baselines

### ISSUE THREAD

**Issue by LeeKeyu** [cv-rits/MonoScene#88]
Hi, thanks for your great work. I recently noticed in the paper (Table 2) that the result of 3D Sketch on dataset NYUv2 (IoU: 49.5, mIoU: 29.2) is much worse than that reported in their original paper (IoU: 71.3, mIoU: 41.1) and also in this survey "3D Semantic Scene Completion: a Survey". 

As you mentioned in the paper that you used the orignal baseline for evaluation in Table 2, could you please explain about the inconsistent results? Thank you a lot in advance.

**Comment by anhquancao** [comment]
Hello @LeeKeyu,
I answered this in the following issues:
https://github.com/astra-vision/MonoScene/issues/5#issuecomment-1000477312
https://github.com/astra-vision/MonoScene/issues/66

**Comment by LeeKeyu** [comment]
Thanks for your quick reply! I understood it. BTW it was a pleasure reading your question-answering comments in [#66](https://github.com/astra-vision/MonoScene/issues/66) it was quite helpful in understanding the topic :)

**Comment by anhquancao** [comment]
You're welcome! I'm glad you found it helpful. If you have more questions, just let me know.
