### ISSUE TITLE
Weird results on Kitti360 

### ISSUE THREAD

**Issue by tuanho27** [cv-rits/MonoScene#9]
Hi @anhquancao, thanks for your great work!

I've tested the inference pipeline on Kitti360 (same sequence) data as your Readme guideline using `monoscene_kitti.ckpt `(kitti sematic) pretrained model, but the visualization results are not as expected. Do you have any idea about this?
![image](https://user-images.githubusercontent.com/22056468/153996025-66498d5f-62b0-4579-9310-1a0b9c3dd491.png)

BRs,
TuanHo

**Comment by anhquancao** [comment]
Hi @tuanho27,
Thank you for pointing out the issue!
I will check it and get back to you after 1 or 2 days. The problem seems to come from the error in the projection pipeline: Velodyne coords -> camera coords -> pixel locations.

**Comment by tuanho27** [comment]
Hi @anhquancao,

Thanks for your quick reply, my friend just pointed out the mistake in line 115 in file` kitti_360_dataset.py`, just change the                 `# T_cam_2_velo` to `self.T_velo_2_cam`, then everything is work well. Thanks to @ngoductuanlhp 

![image](https://user-images.githubusercontent.com/22056468/154016339-b5e3b9d3-a63b-4345-996b-7ba107f28701.png)

BRs,
TuanHo

**Comment by anhquancao** [comment]
Awesome @tuanho27! Many thanks to you and @ngoductuanlhp for fixing this bug. 
I will make the change in the code.
