### ISSUE TITLE
Intuition on Frustum Proportion Loss with non-zeros classes

### ISSUE THREAD

**Issue by haiphamcse** [cv-rits/MonoScene#93]
Hi there, love your work. I recently re-read MonoScene and found an interesting spot, in the paper, it seems that Frustum Proportion Loss is calculated on all voxels inside a frustum. However, in the code I noticed that you only do KL Divergence on non-zero classes, what is the intuition behind this difference? Have you tried to do KL with empty classes?
![image](https://github.com/astra-vision/MonoScene/assets/76871780/859ecccc-6c3e-450b-8b17-dd084b142321)

**Comment by anhquancao** [comment]
Hi @haiphamcse, including an empty class heavily imbalances the class distribution, significantly reducing the probabilities of the other classes. Thus, most frustums will always have >0.9 probability assigned to empty class.
