### ISSUE TITLE
How to change backbone to others such as ResNet50

### ISSUE THREAD

**Issue by haiphamcse** [cv-rits/MonoScene#94]
Hi there, I want to ask can MonoScene use other backbones such as ResNet50 for the 2DUNet? Since you are using code from https://github.com/rwightman/gen-efficientnet-pytorch/blob/master/geffnet/gen_efficientnet.py (which only contains EfficientNet variants), I don't really know how to change to another backbone.

**Comment by anhquancao** [comment]
Hi @haiphamcse , you need to change the encoder to different backbone [in this line](https://github.com/astra-vision/MonoScene/blob/master/monoscene/models/unet2d.py#L165). Then, modify the UNet decoder to take into account the [feature maps of the new backbone](https://github.com/astra-vision/MonoScene/blob/master/monoscene/models/unet2d.py#L96).
