### ISSUE TITLE
about the 3d_recon.gif

### ISSUE THREAD

**Issue by CallMeFrozenBanana** [cv-rits/MonoScene#96]
I find that there is an interesting result but it wasn't mentioned in the repo:
https://github.com/astra-vision/MonoScene/blob/master/teaser/3d_recon.gif
How did it get? Thanks so much~

**Comment by anhquancao** [comment]
Hi, it comes from another work of mine https://github.com/astra-vision/SceneRF
Sorry for this confusion.

**Comment by CallMeFrozenBanana** [comment]
It's useful to me, thanks again~!
