### ISSUE TITLE
Questions regarding NYU Depth V2 class mapping

### ISSUE THREAD

**Issue by curiosity654** [cv-rits/MonoScene#98]
Hello, Thank you for your amazing work! I have some questions about the NYU dataset.

First I would like to know the original source of the dataset you use. As the only occupancy annotation seem to be provided by the paper "Predicting Complete 3D Models of Indoor Scenes", but did not find relative code for conversion.

Second, in monoscene/data/NYU/preprocess.py there is a manual mapping from 37 classes to 12 classes, and the class names are in params.py. I am interested in experimenting on the 37 class version, but I can't find the label mapping for it.

**Comment by anhquancao** [comment]
Hi, I took the data and the setting from this work.
https://github.com/charlesCXK/TorchSSC

**Comment by curiosity654** [comment]
Thank you very much, the class mapping can be found here:
https://github.com/shurans/sscnet/tree/61b4060b435fa93798ea1ced2b87c55bee2433bc/matlab_code

**Comment by anhquancao** [comment]
Awesome! Thanks for the info.
